### ISSUE TITLE
关于数据一致性的疑问

### ISSUE THREAD

**Issue by thbourlove** [douban/douban-mc#4]
不知道你们对于数据一致性是怎么考虑的。在我看来默认情况下，cache 这个装饰器就是一个无锁的实现方式，那么douban是否有做什么其他工作来保证缓存中的数据与数据库中的数据的一致性？

**Comment by qingfeng** [comment]
這個庫保證不了情，需要應用自己去保證，所以會出現不一致的情況

**Comment by thbourlove** [comment]
谢谢，赞一下这个答复速度。
